
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anjali
 */
public class games extends javax.swing.JFrame {

    /**
     * Creates new form games
     */
    int turn=2;
    int btnus[]={0,0,0,0,0,0,0,0,0};
    int ponewon[]={0,0,0,0,0,0,0,0,0};
    int psecwon[]={0,0,0,0,0,0,0,0,0};
    int ponewon(){
        if(ponewon[0]==1 && ponewon[1]==1 && ponewon[2]==1 )
        {
            return 1;
        } if(ponewon[3]==1 && ponewon[4]==1 && ponewon[5]==1 )
        {
            return 1;
        }
         if(ponewon[6]==1 && ponewon[7]==1 && ponewon[8]==1 )
        {
            return 1;
        }
          if(ponewon[0]==1 && ponewon[3]==1 && ponewon[6]==1 )
        {
            return 1;
        }
           if(ponewon[1]==1 && ponewon[4]==1 && ponewon[7]==1 )
        {
            return 1;
        }
            if(ponewon[2]==1 && ponewon[5]==1 && ponewon[8]==1 )
        {
            return 1;
        }
             if(ponewon[0]==1 && ponewon[4]==1 && ponewon[8]==1 )
        {
            return 1;
        }
              if(ponewon[2]==1 && ponewon[4]==1 && ponewon[6]==1 )
        {
            return 1;
        }
              
       return 0;
    }
    int psecwon(){
        if(psecwon[0]==1 && psecwon[1]==1 &&psecwon[2]==1 )
        {
            return 1;
        } if(psecwon[3]==1 &&psecwon[4]==1 && psecwon[5]==1 )
        {
            return 1;
        }
         if(psecwon[6]==1 && psecwon[7]==1 && psecwon[8]==1 )
        {
            return 1;
        }
          if(psecwon[0]==1 &&psecwon[3]==1 && psecwon[6]==1 )
        {
            return 1;
        }
           if(psecwon[1]==1 &&psecwon[4]==1 && psecwon[7]==1 )
        {
            return 1;
        }
            if(psecwon[2]==1 &&psecwon[5]==1 && psecwon[8]==1 )
        {
            return 1;
        }
             if(psecwon[0]==1 && psecwon[4]==1 && psecwon[8]==1 )
        {
            return 1;
        }
              if(psecwon[2]==1 && psecwon[4]==1 && psecwon[6]==1 )
        {
            return 1;
        }
              
       return 0;
    }

    public games() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        b11 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        b3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 0, 102));
        b3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(0, 0, 102));
        b2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 102));
        b4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(0, 0, 102));
        b5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 0, 102));
        b6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 102));
        b1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(0, 0, 102));
        b7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b8.setForeground(new java.awt.Color(0, 0, 102));
        b8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        b9.setForeground(new java.awt.Color(0, 0, 102));
        b9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        b11.setBackground(new java.awt.Color(0, 204, 204));
        b11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b11.setText("Exit");
        b11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b10.setBackground(new java.awt.Color(0, 204, 204));
        b10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b10.setText("Play Again");
        b10.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(266, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b11, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(b10, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Calibri", 3, 48)); // NOI18N
        jButton1.setText("TIC TAC TOE");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
      if(btnus[0]==0)  {
        if(turn%2==0)
        {
            turn++;
            b1.setText("X");
            btnus[0]=1;
            ponewon[0]=1;
            int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }
        else{
        turn++;
        b1.setText("O");
          btnus[0]=1;
          psecwon[0]=1;
          int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
          
        }
      }
      else{
          JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
      }
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        if(btnus[1]==0){
         if(turn%2==0)
        {
            turn++;
            b2.setText("X");
            btnus[1]=1;
             ponewon[1]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
            
        }
        else{
        turn++;
        b2.setText("O");
        btnus[1]=1;
         psecwon[1]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
          
        }}
        else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
      if(btnus[2]==0){
         if(turn%2==0)
        {
            turn++;
            b3.setText("X");
            btnus[2]=1;
             ponewon[2]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
            
        }
        else{
        turn++;
        b3.setText("O");
        btnus[2]=1;
         psecwon[2]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
            
        }}
        else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        if(btnus[3]==0){
         if(turn%2==0)
        {
            turn++;
            b4.setText("X");
            btnus[3]=1;
             ponewon[3]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }
        else{
        turn++;
        b4.setText("O");
        btnus[3]=1;
         psecwon[3]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }}
        else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        if(btnus[4]==0){
         if(turn%2==0)
        {
            turn++;
            b5.setText("X");
            btnus[4]=1;
             ponewon[4]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
            
        }
        else{
        turn++;
        b5.setText("O");
        btnus[4]=1;
         psecwon[4]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }}
        else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(btnus[5]==0){
         if(turn%2==0)
        {
            turn++;
            b6.setText("X");
            btnus[5]=1;
             ponewon[5]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
            
        }
        else{
        turn++;
        b6.setText("O");
        btnus[5]=1;
         psecwon[5]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }}
          else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
        
    }                                  

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
       if(btnus[6]==0){
         if(turn%2==0)
        {
            turn++;
            b7.setText("X");
            btnus[6]=1;
             ponewon[6]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
          
        }
        else{
        turn++;
        b7.setText("O");
        btnus[6]=1;
         psecwon[6]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }}
        else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
    }                                  

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        
        if(btnus[7]==0){
         if(turn%2==0)
        {
            turn++;
            b8.setText("X");
            btnus[7]=1;
             ponewon[7]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }
        else{
        turn++;
        b8.setText("O");
        btnus[7]=1;
         psecwon[7]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
            
        }}
         else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
       
    }                                  

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         
        if(btnus[8]==0){
         if(turn%2==0)
        {
            turn++;
            b9.setText("X");
            btnus[8]=1;
             ponewon[8]=1;
             int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }
        else{
        turn++;
        b9.setText("O");
        btnus[8]=1;
         psecwon[8]=1;
         int r1=ponewon();
            int r2=psecwon();
            if(r1==1){
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 1 HAS WON****");
            }
            else if(r2==1)
            {
            JOptionPane.showMessageDialog(rootPane, "****PLAYER 2 HAS WON****");
            }
           
        }}
         else{
             JOptionPane.showMessageDialog(rootPane, "This option is allready used.");
        }
        
    }                                  

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
       turn=2;
       for(int i=0;i<9;i++)
       {
           btnus[i]=0;
       }
       for(int i=0;i<9;i++)
       {
           ponewon[i]=0;
       }
       for(int i=0;i<9;i++)
       {
           psecwon[i]=0;
       }
    }                                   

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        // TODO add your handling code here:
       this.setVisible(false);
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new games().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}
